agregarAnime('Mahou Shoujo Site', 'Visto', '10');
agregarAnime('Trinity Seven', 'Visto', '10');
agregarAnime('Puella Magi Madoka Magica', 'Visto', '10');
agregarAnime('Gunslinger Girl', 'Visto', '10');
agregarAnime('Fairy Tail', 'Visto', '10');
agregarAnime('Sword Art Online', 'Visto', '10');
agregarAnime('Mahou Shoujo Ikusei Keikaku', 'Visto', '10');
agregarAnime('Prison School', 'Visto', '7');
agregarAnime('Sky Wizards Academy', 'Visto', '8');
agregarAnime('Kill la Kill', 'Visto', '10');
agregarAnime('Absolute Duo', 'Visto', '10');
agregarAnime('Black Lagoon', 'Visto', '8');
agregarAnime('Made in abyss', 'Visto', '10');
agregarAnime('SukaSuka', 'Visto', '10');
agregarAnime('Akame Ga Kill', 'Visto', '10');
agregarAnime('Girls und Panzer', 'Visto', '10');
agregarAnime('Btooom!', 'Visto', '10');
agregarAnime('Hundred', 'Visto', '8');
agregarAnime('Magia Record: PMMG', 'Visto', '10');
agregarAnime('Monster Musume no Iru Nichijou', 'Visto', '10');
agregarAnime('Oregairu', 'Visto', '10');
agregarAnime('Rascal Does Not Dream of Bunny Girl Senpai', 'Visto', '10');
agregarAnime('Darling in the FranXX', 'Visto', '10');
agregarAnime('My Dress-Up Darling', 'Visto', '9');
agregarAnime('Zombie Land Saga', 'Visto', '10');
agregarAnime('Highschool of the Dead', 'Visto', '10');
agregarAnime('High School DxD', 'Visto', '10');
agregarAnime('Masou Gakuen HxH', 'Visto', '8');
agregarAnime('Tokyo Ghoul', 'Visto', '10');
agregarAnime('Elfen Lied', 'Visto', '10');
agregarAnime('School Days', 'Visto', '10');
agregarAnime('Anohana', 'Visto', '10');
agregarAnime('IS: Infinite Stratos', 'Visto', '9');
agregarAnime('Deadman Wonderland', 'Visto', '7');
agregarAnime('Frame Arms Girl', 'Visto', '7');
agregarAnime('Mirai Nikki', 'Visto', '10');
agregarAnime('Angel Beats!', 'Visto', '10');
agregarAnime('Gate: Jieitai Kano Chi nite, Kaku Tatakaeri', 'Visto', '10');
agregarAnime('Date A Live', 'Visto', '10');
agregarAnime('Kami-sama ni Natta Hi', 'Visto', '10');
agregarAnime('Hidan no Aria', 'Visto', '10');
agregarAnime('Gakusen Toshi Asterisk', 'Visto', '8');
agregarAnime('Kantai Collection: KanColle', 'Visto', '8');
agregarAnime('Corpse Party', 'Visto', '10');
agregarAnime('Hitsugi No Chaika', 'Visto', '10');
agregarAnime('Wataten!', 'Visto', '8');
agregarAnime('Military!', 'Visto', '7');
agregarAnime('Kaze no Stigma', 'Visto', '8');
agregarAnime('Jigoku Shojo', 'Visto', '10');
agregarAnime('Aharen-San wa Hakarenai', 'Visto', '10');
agregarAnime('Kakegurui', 'Visto', '10');
agregarAnime('Maojo Oyasumi', 'Visto', '10');
agregarAnime('Jitsu wa Watashi wa', 'Visto', '10');
agregarAnime('Hentai Ouji to Warawanai Neko', 'Visto', '8');
agregarAnime('Cupids Chocolates', 'Visto', '7');
agregarAnime('Kore wa Zombie Desu ka?', 'Visto', '8');
agregarAnime('Seirei Tsukai no Blade Dance', 'Visto', '10');
agregarAnime('Chrono Crusade', 'Visto', '10');
agregarAnime('K-ON!', 'Visto', '10');
agregarAnime('Girls Frontline', 'Visto', '10');
agregarAnime('Saijaku Muhai no Bahamut', 'Visto', '7');
agregarAnime('Kobayashi-san Chi no Maid Dragon', 'Visto', '10');
agregarAnime('Princess Connect! Re:Dive', 'Visto', '10');
agregarAnime('Kiss×sis', 'Visto', '10');
agregarAnime('No Game No Life', 'Visto', '10');
agregarAnime('Kanojo, Okarishimasu','Visto','9.5');
agregarAnime('Maou Gakuin no Futekigousha','Visto','10');
agregarAnime('Day Break Illusion', 'Visto', '10');
agregarAnime('Wixoss', 'Visto', '10');
agregarAnime('Wonder Egg Priority', 'Visto', '7', 'Inconcluso');
agregarAnime('Eromanga Sensei', 'Visto', '10');
agregarAnime('Happy Sugar Life', 'Visto', '10');
agregarAnime('Tejina-Senpai', 'Visto', '10');
agregarAnime('Re:Zero', 'Visto', '10', 'Inconcluso');
agregarAnime('Engage Kiss', 'Visto', '10');
agregarAnime('BanG Dream!', 'Visto', '10', 'Inconcluso');
agregarAnime('Hige wo Soru. Soshite Joshi Kousei wo Hirou', 'Visto', '10');
agregarAnime('Himouto! Umaru-chan', 'Visto', '7');
agregarAnime('BOFURI: I Don`t Want to Get Hurt, So I`ll Max Out My Defense', 'Visto', '10');
agregarAnime('86:Eighty Six', 'Visto', '10');
agregarAnime('The Quintessential Quintuplets', 'Visto', '10');
agregarAnime('Spy × Family', 'Visto', '7');
agregarAnime('Yumemiru Danshi wa Genjitsushugisha', 'Visto', '7');
agregarAnime('Shumatsu no Harem', 'Visto', '10');
agregarAnime('Jahy-sama wa Kujikenai!', 'Visto', '8');
agregarAnime('Ishuzoku Reviewers', 'Visto', '10');
agregarAnime('Isekai Quartet', 'Visto', '7');
agregarAnime('Kawaii dake ja Nai Shikimori-san', 'Visto', '8');
agregarAnime('Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai', 'Visto', '8');
agregarAnime('New Game!', 'Visto', '8');
agregarAnime('Mieruko-chan', 'Visto', '10');
agregarAnime('Assault Lily BOUQUET', 'Visto', '8');
agregarAnime('Senpai ga Uzai Kōhai no Hanashi', 'Visto', '8');
agregarAnime('Osananajimi ga Zettai ni Makenai Love Comedy', 'Visto', '7');
agregarAnime('Takt Op.Destiny', 'Visto', '9.5');
agregarAnime('Overflow', 'Visto', '4');
agregarAnime('Sin: Nanatsu no Taizai', 'Visto', '6');
agregarAnime('Cyberpunk: Edgerunners', 'Visto', '7');
agregarAnime('Futoku no Guild', 'Visto', '6');
agregarAnime('Gleipnir', 'Visto', '10', 'Inconcluso');
agregarAnime('Nande Koko ni Sensei ga!?', 'Visto', '9');
agregarAnime('Gabriel Dropout', 'Visto', '7.5');
agregarAnime('Dark Gathering', 'Visto', '10');
agregarAnime('Tantei wa Mou, Shindeiru', 'Visto', '10');
agregarAnime('Violet Evergarden', 'Visto', '10');
agregarAnime('Boku no Kanojo ga Majime Sugiru Shojo Bitch na Ken', 'Visto', '7');
agregarAnime('Paradox Live the Animation', 'Visto', '7');
agregarAnime('16bit Sensation: Another Layer', 'Visto', '10');
agregarAnime('Potion-danomi de Ikinobimasu!', 'Visto', '10');
agregarAnime('Fluffy Paradise', 'Visto', '7');
agregarAnime('Himesama "Goumon" no Jikan desu', 'Visto', '7');
agregarAnime('Pon no Michi', 'Visto', '6');
agregarAnime('Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita.', 'Visto', '10');
agregarAnime('Sekai Saiko no Ansatsusha, Isekai Kizoku ni Tensei Suru', 'Visto', '10');
agregarAnime('Val x Love', 'Visto', '8', 'Inconcluso');
agregarAnime('Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?', 'Visto', '8');
agregarAnime('Bikini Warriors', 'Visto', '5');
agregarAnime('Hinako Note', 'Visto', '7');
agregarAnime('RPG Real Estate', 'Pendiente', '0');
agregarAnime('Joze to Tora to Sakanatachi', 'Pendiente', '0');

agregarAnime('Wind Breaker', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Yoru no kurage wa oyogenai', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Kami wa game ni ueteiru', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Blue Archive: The animation', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Vampire Dormitory', 'Estreno', '0', 'Sin Estrenar');

agregarAnime('Tokidoki Bosotto Roshia-Go de Dereru Tonari no Arya-San', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Junior High School DxD', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('2.5 Jigen no Yuwaku', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Unnamed Memory', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Hoshifuru Oukoku no Nina', 'Estreno', '0', 'Sin Estrenar');
agregarAnime('Isekai Cheat Magician', 'Estreno', '0', 'Sin Estrenar');
